name: TuSKe
description: A Skript Addon which has some managers, such as custom enchantments, recipes and GUI inventory, and some general stuffs.
main: com.github.tukenuke.tuske.TuSKe
version: @version@
author: Tuke_Nuke
depend: [ Skript]
softdepend: [ ProtocolSupport, ViaVersion, Umbaska, SkQuery ] #Last two dependencies are just to not register ClickType and InventoryType before them
api-version: 1.18
commands:
  tuske:
    description: Main command for TuSKe
    usage: /tuske
    permission: tuske.admin
    permission-message: §cYou don't have permission for this command!
permissions:
  tuske.admin:
    description: Access to /tuske.
    default: op